alg_name: "FT"
model_name: /home/zhuliyi/LLM_bases/gpt2 
# layers: [4,5,6,7,8]
layers: []
device: 2
num_steps: 40
batch_size: 1
max_length: 40
# lr: 3e-1
# lr: 6e-1    # √ 新方法
# lr: 9e-1    # √√√ 新方法
lr: 1.5       # √√√ 新方法

weight_decay: 0
kl_factor: 0
norm_constraint: 5e-4
grad_norm_constraint: 5e-4
num_return_sequences: 1
max_new_tokens: 3
static_target: False
sample_with_context: False
target_update_interval: 1
temperature: 100.0
print_kl: False

M_name: gpt2
n_layer: 12
n_embd: 768
prefix_layer: 10
subject_layer: 4




# objective_optimization: "target_new"
objective_optimization: "target_and_completion_with_context"
rewrite_module_tmp: "transformer.h.{}.mlp.c_proj"
layer_module_tmp: "transformer.h.{}"
mlp_module_tmp: "transformer.h.{}.mlp"
attn_module_tmp: "transformer.h.{}.attn"
ln_f_module: "transformer.ln_f"
lm_head_module: "transformer.wte"
model_parallel: False
