alg_name: "FT"
model_name: /home/zhuliyi/LLM_bases/Llama-2-7b-hf
device: 1
# layers: [4, 5, 6, 7, 8]
layers: []
num_steps: 30
batch_size: 1
max_length: 40
# lr: 7e-4
lr: 7e-2
weight_decay: 0
kl_factor: 0
norm_constraint: 5e-4
grad_norm_constraint: 5e-4
num_return_sequences: 1
max_new_tokens: 3
static_target: False
sample_with_context: False
target_update_interval: 1
temperature: 100.0
print_kl: False

M_name: llama-2-7b
n_layer: 32
n_embd: 4096
prefix_layer: 1
subject_layer: 12


objective_optimization: "target_and_completion_with_context"
rewrite_module_tmp: "model.layers.{}.mlp.down_proj.weight"
layer_module_tmp: "model.layers.{}"
mlp_module_tmp: "model.layers.{}.mlp"
attn_module_tmp: "model.layers.{}.self_attn"
ln_f_module: "model.norm"
lm_head_module: "lm_head"
model_parallel: False
